### ISSUE TITLE
Split the config for server and client

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#170]

**Comment by kushsharma** [comment]
Why do we need to do that?

**Comment by irainia** [comment]
> Why do we need to do that?

If we look at the current config, it contains several values, where some are grouped with its own purpose and some are not. Usually, we run Optimus in two modes, as the client and as the server, making it not straightforward which config is for which mode. And in the implementation, we pass some config values that are actually not needed for one mode. If we have a better separation, then it will be easier to maintain. For example, when we are running in the server, we only need the following configs and for when running the client, we need the following config.

cc: @sravankorumilli

**Comment by kushsharma** [comment]
Optimus generates a single CLI binary, its just matter of use how you want to use it. It can be run as a server or a client interacting with the server. When you use in production, you won't be using it for both situation at the same time. A single config will be used for one thing only. Because both of these modes are part of main optimus, splitting config just based on cli modes doesn't look a better design choice to me.

Optimus has a `serve` section for the server mode which is exclusive for this only, how is this confusing? Maintaining one config file vs maintaining two config file, which is more hassle?

> If we look at the current config, it contains several values, where some are grouped with its own purpose and some are not.

Can you give an example @irainia 

> no clear separation between config used on server and config used on client (aka project repo) that lead to confusion

Lead to confusion to whom? CLI users for deploy and other commands? @deryrahman 

Okay, let me give an example, if I want to expose a config related to plugins like, custom directory to look for plugins, where should it go? New client config or new server config?

**Comment by ravisuhag** [comment]
Optimus will have two sets of users. people who deploy server and rest who use Optimus to manage jobs to interact with the server. 
IMO, Server config should be provided on the fly. And not managed in any file or so. 
As an example. `optimus serve -c config.yaml` When we start the Optimus server we should pass the config file. It should also be able to accept env params. 
While on the other hand, for optimus cli config, I think we should have `optimus config init` which init config in user home location. This config should only be related to Optimus client and no config of server should be leaked in it. I have abstracted out the loading of this config in salt package actually. 
https://github.com/odpf/salt/blob/main/cmdx/config.go
Still have a few improvements to be made. If this sounds good idea then I think it will require us to split the structs for server and client configs. A similar implementation can be found in Guardian.

**Comment by kushsharma** [comment]
Optimus config in home directory won't work nicely, we use that config to organise projects. Keeping it in home directory(for clients) is restricting it to be used with only one project where as keeping it in a git directory of project will scope it out to only that project. @ravisuhag 

`optimus serve -c config.yaml` I agree providing this explicitly to override the config file make sense but I guess there should be a default location as well where the binary can look on its own right?

In an actual use case, a config file will never have both already according to design, unless you are a developer and experimenting something. Why do you think we are `leaking` server config at the moment?

**Comment by ravisuhag** [comment]
Yes, fair enough for the first part. We can treat client config as root level as a project level. Something on the lines of global .gitignore and the local one. Any global config users want to put they can put at home. 

Yes, even if there is a default location. Sever config we can go with the thought that the scope of that is only limited to server command and it does not mix with the client config at all. 
The way I see server config from a user perspective is that they only need to take that into account when they start the server. I think even behind the scene, code can also reflect that. wdyt?

**Comment by kushsharma** [comment]
> Any global config users want to put they can put at home.

Although I think it will be difficult for users to trace which config is effecting a certain behaviour when we choose to go with hierarchical configs but okay, not a big deal, thats a different problem we can discuss separately. 

> The way I see server config from a user perspective is that they only need to take that into account when they start the server.

This is already true with the current design. We have different `keys` for client and server configs. Thats what I am confused, why do we think splitting it into two files will achieve this?

> it does not mix with the client config at all

Help me understand a single user behaviour example where its mixing right now? 😄

**Comment by kushsharma** [comment]
Think if it in this way, why did we choose to go with one binary for client and server and not two? Why do you think users are not confused with which command to run(client/server) and now we think they will get confused with configs?

Also you know this will also cause lot of duplication in configs right? Things that goes in both cases like log levels, plugin directories, etc.

**Comment by sravankorumilli** [comment]
If we look at the current config then there are few areas it is little confusing.

1. when someone looks at the config the first time, then it appears the serve section is the only section for server config, but there are other configs which needs to be configured for server.
2. host & serve.ingress_host, server.host what is used for what is another instance.

I believe because of these primary concerns, it is not very clear when we are consuming configs which configs we expect to be available and not available.

IMO, either.
1. We can have a clear segregation for client & server configs even if that means a duplication(log_level,plugin_path), everything defined in the optimus.yaml though
2. Or we avoid duplication and provide configs for both client & server combined, then we can have a single config for clients to reach optimus server avoid rest all (host,serve.ingress_host,serve.host), until & unless we process these configs differently.

From implementation point of view,  in both the options we can have additional structs for Client&Server configs, such that it is clear for the developer on what configs to use on when acting as a client & what configs to use when optimus is deployed as server. The only place to bother about that is while preparing that client & server configs.

**Comment by deryrahman** [comment]
From implementation point of view, I agree we need to have 2 struct, to define server config and client config. @sravankorumilli . But for the how we define the config in `.optimus.yaml`, I've several concern on that.

For the first suggestion, I believe it can be much cleaner because we explicitly define client and server config in single `.optimus.yaml`. For example, our config will be looked like this

```yaml
...
client:
    log_level: 
    project:
        name:
        config:
    namespace:
        name:
        ...
server:
    log_level: 
    host:
    port:
    ...
...
```
But the drawback is, there's no case we run optimus in both mode, so there's no point we put field `client` on current project directory as well as there's no point we put field `server` in home directory.

For the second suggestion, we can have combined config without explicitly define the mode. The pros is, we can have a lot of flexibility and avoid duplication. For example, on our home directory, we can have config like this
```yaml
log_level: 
host:
port:
...
```
On our project dir, we can have config like this
```yaml
log_level:
project:
    name:
    config:
    ...
```

The drawback is, we're mixing the server and client in `.optimus.yaml`. But, as long as we have a clear comment in `.optimus.sample.yaml` on which part is using on which mode, it's not an issue.

For both approach, we still need to have separate struct. Not a combined one as we currently have now.

**Comment by deryrahman** [comment]
I'm partially concluding our discussion, let me know if there's anything missing / uncovered

1. we can pass config explicitly if we want to run the server as @ravisuhag [suggested](https://github.com/odpf/optimus/issues/170#issuecomment-1061105589), but still provide default location to load the config (@kushsharma concern) as well as from env param. So, server command will use config from env, explicit flag `-c .theconfig.yaml`, `exec_binary_location`, and `home_root` respectively
2. for the client commands, the config will be loaded from explicit and `current_project_dir`. I agree that loading config from home dir won't work nicely for organize project as @kushsharma [mentioned](https://github.com/odpf/optimus/issues/170#issuecomment-1061619218)
3. as @sravankorumilli mentioned, our server config is not only defined from field `serve` but also `scheduler` and `log`. Either we can have clear separation in `.optimus.yaml` or combine both, we still need 2 struct for clear separation readability as developer

**Comment by ravisuhag** [comment]
@deryrahman 
I would also recommend using `optimus.yaml` name only for client config and always use `config.yaml` for server config default and keeping these two files separate to draw a clear distinction.
