### ISSUE TITLE
Use Init Containers instead of baking the optimus client with the executor

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#362]
As part of this rfc https://github.com/odpf/optimus/blob/main/docs/docs/rfcs/20220507_simplify_plugin_maintenance.md

Using init containers helps us avoid releasing all plugin executors everytime there is a change in the optimus client interactions with the server or any improvement in the initial boot process.

**In the scope** 

1. Use init containers to provide the assets and environment variables to executor container and all the plugins will be updated to not bake another executor image and use directly the executor image.
2. Launch of Container will be updated with the init container strategy.
3. Plugins Servers will be configured with the executor images directly.

**Comment by kushsharma** [comment]
When we decided to download optimus binary instead of using init containers, the idea was to keep the support for docker as an executor because it doesn't have this concept of init containers. I think this will simplify the maintenance but will tie Optimus to only work with Kubernetes. So are we okay with this restriction or should we think of alternative approach to ease the bootstrap?

**Comment by sravankorumilli** [comment]
In the current scope we can go with kube native solution. Later if don't want to tie ourselves with kube which i don't see any need in any near future then we can follow a similar approach.

**Comment by ravisuhag** [comment]
@sravankorumilli can this be closed, given pr is merged?
