### ISSUE TITLE
Plugin Manager : Support Basic Plugin Manager to install plugins

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#363]
**Description**
As part of this, Plugin Manager component will be introduced to install plugins in the configured location declaratively.
Plugins will be configured in the config.yaml  as per the specification.
Refer [RFC : Simplify plugins](https://github.com/odpf/optimus/blob/main/docs/docs/rfcs/20220507_simplify_plugin_maintenance.md)
Depends on : #410 

**Acceptance Criteria**

- [x] Install plugins through which are available through `https, gcs, file` locations.
- [x] User should be able to install plugins in the configured directory.

**Out of Scope**

1. Installation of plugins which needed auth is out of scope for this.

**Tech Details**

**Comment by sravankorumilli** [comment]
As part of this, Plugin Manager will be introduced to install plugins in the configured location.
Plugins will be configured in the optimus.yaml  as per the specification.
`optimus plugin install` will be the command used for installing. This will be the new way of installing plugins on client as well as server.

**Scope**
1. Installing Plugins through a file provider.
2. Updating the plugins
3. No more auto plugin discovery.

**Comment by SaikumarChintada** [comment]
rather than developing custom plugin manger, using well supported (go-getter)[https://github.com/hashicorp/go-getter] seems to be opportunistic. It has well supported providers for different protocols.

Plugin installation/management will be just a bash script that cleans the plugin dir and makes a fresh install.
Plugin config will be list of artifact links in a text file.

**Comment by ravisuhag** [comment]
@SaikumarChintada agree with using go-getter. Can you highlight on what all will this bash script will do. Also how about if we use go-getter as a lib and provide proper Optimus binary command for management?

**Comment by sravankorumilli** [comment]
Yes we will be using go getter as a library

**Comment by smarch-int** [comment]
gcs support has limitations due to go-getter library.
* `gs://<bucket_name>/<file_path_inside_bucket>` doesnot seems to be possible.
* Only the following uri patterns are supported:
  - gcs::https://www.googleapis.com/storage/v1/bucket 
  - gcs::https://www.googleapis.com/storage/v1/bucket/foo.zip
  - http://www.googleapis.com/storage/v1/bucket/foo    [supported since just http(s)]
