### ISSUE TITLE
Refactor observers across Optimus

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#430]
As part of this card, we would expect observers usage and implementation to be standardized, currently the way observers is used involves some processing on the client side, rather it would be better if through observers all the information is passed in a direct consumable fashion such that clients just log. 

**Scope**
1. Events are not standardized - event naming.
2. Optimus CLI we are extra processing after consuming these events rather we can avoid and just the log the events.

**Comment by deryrahman** [comment]
After I went through the codebase, there are several causes which make our observers are not maintainable. But, before that, I want to make sure that we have a same definition about the observer.

```
Observer has responsibility to notify any events through any medium.
```

Our observers are not properly placed, they are scattered and not standard. In optimus, there are 2 type of observers based on their medium:

| Type | Example | Usage |
|---|---|---|
| Pipeline Observer | [pipelineLogObserver](https://github.com/odpf/optimus/blob/e82229d5b2cf53e0b2a063c046971fde4401e93e/cmd/server/dependencies.go#L137) | notify message through logger |
| Stream Observers | [resourceObserver](https://github.com/odpf/optimus/blob/e82229d5b2cf53e0b2a063c046971fde4401e93e/api/handler/v1beta1/observer.go#L14) | notify message through resource stream |
| | [jobCheckObserver](https://github.com/odpf/optimus/blob/e82229d5b2cf53e0b2a063c046971fde4401e93e/api/handler/v1beta1/observer.go#L75) | notify message through job check stream |
| | [jobRefreshObserver](https://github.com/odpf/optimus/blob/e82229d5b2cf53e0b2a063c046971fde4401e93e/api/handler/v1beta1/observer.go#L108) | notify message through job refresh stream |
| | [jobDeploymentObserver](https://github.com/odpf/optimus/blob/e82229d5b2cf53e0b2a063c046971fde4401e93e/api/handler/v1beta1/observer.go#L169) | notify message through job deployment stream |
| | ... | .. |

If we want to add observer in component (handler, service, etc), new observer need to be introduced. Even though we can use existing observer, but using `jobRefreshObserver` on deployment service is not proper. As we need to add new observer again and again, we can use only 1 stream observer.

Here's the rough UML for the observers:

![image](https://user-images.githubusercontent.com/3104624/177662814-fc9a7611-93a8-433d-b00e-e9b90fe116a9.png)

We can put it inside `core/progress` package

Apart from that, our events are also not standard. Event type [need to be check in server side](https://github.com/odpf/optimus/blob/e82229d5b2cf53e0b2a063c046971fde4401e93e/api/handler/v1beta1/observer.go#L181), before the response is passing through grpc stream. Response is transferred to client. And response type also [need to be checked in client side](https://github.com/odpf/optimus/blob/e82229d5b2cf53e0b2a063c046971fde4401e93e/cmd/deploy/deploy.go#L445). 

We have a goal to make client as dumb as possible, so that the client would have single responsibility on how to display the message. How the message is constructed is server responsibility.

```go
	for {
		resp, err := stream.Recv()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return "", err
		}

                // looping
                progress := resp.GetProgress()
                if progress != nil {
                        x.logger.Info(progress.Msg)
                        continue
                }

                // termination state
                if resp.Success {
                        x.logger.Info(resp.Msg)
                        return nil
                } else {
                        return resp.Err
                }
        }
```

**Comment by sravankorumilli** [comment]
I believe the problem is not the observers, the problem is the api contract is not very meaningful and that happened because, the api does things in async and still is long running in certain situations. 
If the api is just long running and doing things in sync the contract would be clean and it just needs a simple response_sender to encapsulate  and stream the responses.
If the api is async then there is no need to send a stream of responses the entire response can be send immediately and the async operation details will be captured in the DB.
What that means in Optimus is move dependency resolution async and the apis should n't be streaming responses.

**Comment by sbchaos** [comment]
We do not have any well defined domain events or the event processing related components.
All the events just carry a name, and are used only for logging purpose, which can be better done easily with status enums.

On the point about api contracts not being meaningful, we should define if we want to keep long running process as
1 sync and streaming
2 async and non-streaming, containing all errors in the api.

If we go ahead with async route, then we can make dependency resolution async as in operations like refresh it might take a long time.

**Comment by irainia** [comment]
> We have a goal to make client as dumb as possible, so that the client would have single responsibility on how to display the message. How the message is constructed is server responsibility. Below is pseudocode on how client should process the response:
...

If our goal is to make the client as dumb as possible, then I'm curious how we will implement it mas @deryrahman . If we look at the pseudo code you mentioned, there seems to be no observer being invoked or called. I assume it's running behind the scene, correct me if I missed it. The reason I assumed so is if we want to make the client as dumb as possible, then the observer should be separated from the response handling (be it stream or not stream request/response). This is because at some point, the server might return value that needs the client to handle it differently, like marking the execution as failed or success.

However, if my assumption missed, then perhaps we need to redefine what observer is in Optimus, what its responsibility, etc.; or at least reconsider what kind of "event" to be sent through the observer and which to be sent as a response.

**Comment by deryrahman** [comment]
@sravankorumilli @sbchaos yes, I believe our events are just for logging purpose. In most of our case, I didn't see any urgency to carry any other things than message in our event. I spot 1 event that carry `deploymentID`. I'm not sure if we can called it as an event. But if we aimed to make it as an event that should be passed through observer, we can restructure the event something like this

```
event:
  - progressEvent -> hold to log / inform the progress to the client
  - deploymentEvent -> send the deploymentID to client for further processing
```

But I suggest we shouldn't treat deploymentID as an event that need to be pass to the observers. The purpose of observer is to give information about what to observe. In this case, we want to observe the progress. Would it be stated as success, error, or warning.

mas @irainia yes, the pseudocode is just a high level of what we want to aim. I haven't written the detail about how the server call the observer to invoke the message.

> The reason I assumed so is if we want to make the client as dumb as possible, then the observer should be separated from the response handling (be it stream or not stream request/response). This is because at some point, the server might return value that needs the client to handle it differently, like marking the execution as failed or success.

I have spiked for a while, I think we don't need to separate the observer from response handling, we can add 1 field. E.g. event, and attach it to the response proto who need observer progress.


@all if needed, I provide a prototype about the solution above as well as what I have discussed with @sravankorumilli yesterday
Can see in here https://github.com/odpf/optimus/compare/spike-refactor-observer?expand=1

**Comment by deryrahman** [comment]
@sravankorumilli We have already had a discussion to conclude the approach. To remove any complexity, we agree to the following things:
- Remove the observers entirely, just use stream itself do message sending (add wrapper to limit the ability of the stream, only `Send`)
- Redefining the protobuf on deployJobSpecificationResponse + any response's proto that need Log status to be sent

e.g. on DeployJobSpecificaionResponse
```go
type DeployJobSpecificaionResponse struct {
	DeploymentID string
	LogStatus Log
}

type Log struct {
	Level string // info, warn, err
	Message string
}
```

Client only print the message if the response hold the LogStatus. If it is good enough, then we can do an implementation @sravankorumilli 

cc: @irainia @sbchaos

**Comment by deryrahman** [comment]
mba @arinda-arif & mas @irainia , as we're planning to simplify the event processing in client side, restructuring the correlated response protos need to be taken. I spotted 2 more proto need to be change, DeployResource and Refresh. Other than the below fields, will be deprecated. Let me know about this struct if you have concerns

```go
type DeployResourceSpecificationResponse struct {
	ResourceName string
	LogStatus Log
}

type RefreshJobsResponse struct {
	DeploymentID string
	LogStatus Log
}
```

**Comment by irainia** [comment]
> mba @arinda-arif & mas @irainia , as we're planning to simplify the event processing in client side, restructuring the correlated response protos need to be taken. I spotted 2 more proto need to be change, DeployResource and Refresh. Other than the below fields, will be deprecated. Let me know about this struct if you have concerns
> 
> ```go
> type DeployResourceSpecificationResponse struct {
> 	ResourceName string
> 	LogStatus Log
> }
> 
> type RefreshJobsResponse struct {
> 	DeploymentID string
> 	LogStatus Log
> }
> ```

So far, no concern from me.
