### ISSUE TITLE
Support custom date range generation via SQL query

### ISSUE THREAD

**Issue by pikochip** [odpf/optimus#73]
Right now on Optimus, date range is generated by this `window` config in `task` section on `job.yaml` file
```
window:
    size: 24h
    offset: 24h
    truncate_to: d
```
On some of our use cases, we need to generate a custom date range based on certain conditions in form of SQL query. For example:
```
SELECT DISTINCT DATE(event_date) as data_date
FROM some_table
WHERE (event_date >= start_date and event_date < end_date)

UNION DISTINCT

SELECT DISTINCT DATE(created_date) as data_date
FROM some_table_2
WHERE ((created_date >= start_date AND created_date < end_date)  
OR (last_modified_date >= start_date AND last_modified_date < end_date))
ORDER BY 1
```
Date range that generated by above query then will be used as parameters to the job.

**Comment by pikochip** [comment]
Some proposed solution:
- We can put the date_list query directly in `job.yaml` (ex: add `date_list_query` as additional parameter on `window` config)
```
window:
    size: 24h
    offset: 24h
    truncate_to: d
    date_list_query: > 
      SELECT DISTINCT DATE(event_date) as data_date 
      FROM some_table 
      WHERE (event_date >= start_date and event_date < end_date)
```
- We can put the query as additional `assets` (ex: `assets/date_list.sql`) and put a parameter in the job config that indicates the job will use the date_list query instead of default window config.
```
## assets/date_list.sql
SELECT DISTINCT DATE(event_date) as data_date
FROM some_table
WHERE (event_date >= start_date and event_date < end_date)
```
```
## job.yaml
window:
    use_custom_date_list: true 
    size: 24h
    offset: 24h
    truncate_to: d
```

**Comment by kushsharma** [comment]
Having something like 
```yaml
date_list_query: > 
      SELECT DISTINCT DATE(event_date) as data_date 
      FROM some_table 
      WHERE (event_date >= start_date and event_date < end_date)
```
will not fit in what Optimus is trying to do, that is, we can't make it specific to BigQuery SQL queries that is for sure.
Now the second proposed solution can be used but will be a little tricky to implement because `DSTART` and `DEND` macro variables get compiled as part of `assets` before they are sent to the `bq2bq` task for execution because of which replacing them inside the task where the query is already compiled with some existing window parameters would complicate things.

I have something different in mind that will be generic enough to fit in all use cases(including this) and would not look this hacky.

We can create a prehook that generates these window date parameters, this hook could be agnostic of what the task is, in our case it's BQ SQL query but for a different task, it could be something else. This window hook after executing the query will save these window start and end to Optimus database as key/value pairs. Now, this storing temporary key/value pair is not yet supported but we can support this which will work as `Inter Task Communication(ITC)` for downstream jobs. If a parent instance in the execution hierarchy saves something in this shared key/value store, the rest of the instances(task/hook) will inherit these configs for their use case. Using this analogy, we can ask the topmost instance to generate window parameters, store them in Optimus db(k/v store) as `DSTART` & `DEND` and then further `bq2bq` task when requests its assets will get compiled with these generated window parameters.

**Comment by sravankorumilli** [comment]
If this is needed mainly for filtering data you can define that logic in the SQL query. @kushsharma by decoupling windowing configuration for upstream dependency resolution & letting users define the filters with in sql query based on run_date or any custom logic should solve these behaviours, instead of going via inter task communication.

If the upstream job dependencies need to be resolved based on the query result, I don't think we can support them at the moment.
